# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pr:
- '*'

pool:
  name: website-pool
  demands:
  - Agent.Name -equals website-blog

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    
    - script: | # Debugging step to list files in the source directory
        dir -R $(Build.SourcesDirectory)
      displayName: 'List Source Files'

    - script: | # Build your HTML and CSS files (No actual compilation, just copying)
        mkdir -p $(Build.BinariesDirectory)/.
        copy -R * $(Build.BinariesDirectory)/./
      displayName: 'Copy Website Files'

    - publish: $(Build.BinariesDirectory)/.
      artifact: drop
      displayName: 'Publish Website Files'

- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: 'your-environment-name'  # Create an environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - script: |
              # Deploy your website to a hosting platform of your choice (e.g., Azure Blob Storage, GitHub Pages)
              # Replace with your deployment commands and settings
            displayName: 'Deploy Website'
