# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
     - '*'

pr:
- '*'

pool:
  name: website-pool
  demands:
  - Agent.Name -equals website-blog

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: | # Build your HTML and CSS files (No actual compilation, just copying)
        mkdir -p $(Newdir)/website
        copy -R * $(Newdir)/website/
      displayName: 'Copy Website Files'

    - publish: $(Build.BinariesDirectory)/website
      artifact: drop
      displayName: 'Publish Website Files'

- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: New-deploy  # Create an environment in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'website'

          - script: |
              # Deploy to GitHub Pages
              echo "Deploying the website to GitHub Pages..."
              git config --global user.email "you@example.com"
              git config --global user.name "Your Name"
              git checkout --orphan gh-pages
              cp -R $(Pipeline.Workspace)/current/* .
              git add --all
              git commit -m "Azure DevOps CI/CD deployment"
              git push origin gh-pages --force
            displayName: 'Deploy to GitHub Pages'
